#!/bin/bash
echo "████████╗░██████╗░███████╗██████╗░"
echo "╚══██╔══╝██╔════╝░██╔════╝██╔══██╗"
echo "░░░██║░░░██║░░██╗░█████╗░░██████╦╝"
echo "░░░██║░░░██║░░╚██╗██╔══╝░░██╔══██╗"
echo "░░░██║░░░╚██████╔╝███████╗██████╦╝"
echo "░░░╚═╝░░░░╚═════╝░╚══════╝╚═════╝░"
echo "Welcome to the TGEB setup process!"
echo "Installing termux-api..."
yes | pkg install termux-api -y > /dev/null 2>&1
echo "Done."

echo "Installing Python..."
yes | pkg install python -y > /dev/null 2>&1
echo "Done."

echo "Installing pip libraries..."
pip install -r requirements.txt > /dev/null 2>&1
echo "Done."

echo "Adding x11-repo..."
yes | pkg install x11-repo -y > /dev/null 2>&1
echo "Done."


echo "Adding tur-repo..."
yes | pkg install tur-repo -y > /dev/null 2>&1
echo "Done."


echo "Installing Chromium..."
yes | pkg install chromium -y > /dev/null 2>&1
echo "Done."


# Ask for the user's token, debug token, group, and address
read -p "Enter your group: " group
read -p "Enter your address: " address
read -p "Enter your token: " token
read -p "Enter your debug token: " debug_token
read -p "Enter an admin: " admin

# Ensure the electricity_bot directory exists
mkdir -p electricity_bot

# Create the Python file with the stored variables in the electricity_bot directory
cat <<EOL > electricity_bot/config.py
# This file is auto-generated by the setup script

GROUP = "$group"
ADDRESS = "$address"
TOKEN = "$token"
TOKEN_DEBUG = "$debug_token"

admins = [$admin]

EOL

echo "File config.py has been created in the electricity_bot directory. You're all set!"
echo "Starting up the bot..."

python3 main.py