#!/bin/bash

# Color codes
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m' # No Color

echo -e "████████╗░██████╗░███████╗██████╗░"
echo -e "╚══██╔══╝██╔════╝░██╔════╝██╔══██╗"
echo -e "░░░██║░░░██║░░██╗░█████╗░░██████╦╝"
echo -e "░░░██║░░░██║░░╚██╗██╔══╝░░██╔══██╗"
echo -e "░░░██║░░░╚██████╔╝███████╗██████╦╝"
echo -e "░░░╚═╝░░░░╚═════╝░╚══════╝╚═════╝░"
echo -e "Welcome to the TGEB setup process!"
echo -e "Installing termux-api..."
yes | pkg install termux-api -y > /dev/null 2>&1
echo -e "${GREEN}Done.${NC}"

echo -e "Installing Python..."
yes | pkg install python -y > /dev/null 2>&1
echo -e "${GREEN}Done.${NC}"

echo -e "Installing pip libraries..."
pip install -r requirements.txt > /dev/null 2>&1
echo -e "${GREEN}Done.${NC}"

echo -e "Adding x11-repo..."
yes | pkg install x11-repo -y > /dev/null 2>&1
echo -e "${GREEN}Done.${NC}"

echo -e "Adding tur-repo..."
yes | pkg install tur-repo -y > /dev/null 2>&1
echo -e "${GREEN}Done.${NC}"

echo -e "Installing Chromium..."
yes | pkg install chromium -y > /dev/null 2>&1
echo -e "${GREEN}Done.${NC}"

echo -e $"\nGreat! Now let's configure some of the settings:\n" 

read -p "Enter your group: " group
read -p "Enter your address: " address
read -p "Enter your token: " token
read -p "Enter your debug token: " debug_token
read -p "Enter an admin: " admin

mkdir -p electricity_bot

cat <<EOL > electricity_bot/config.py
# This file is auto-generated by the setup script

GROUP = "$group"
ADDRESS = "$address"
TOKEN = "$token"
TOKEN_DEBUG = "$debug_token"

admins = [$admin]

EOL

echo -e "${GREEN}File config.py has been created in the electricity_bot directory. You're all set!${NC}"
echo -e "Starting up the bot..."

python3 main.py
